<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Visibility extends Model
{
    use HasFactory;

    protected $fillable = [
        'is_messenger',
        'is_disqus',
        'is_google_analytics',
        'is_add_this_status',
        'is_announcement',
        'is_maintainance_mode',
        'is_blog_share_links',
        'is_tawk_to',
        'is_recaptcha',
        'is_cooki_alert',
        'is_about_page',
        'is_service_page',
        'is_poerfolio_page',
        'is_package_page',
        'is_team_page',
        'is_faq_page',
        'is_blog_page',
        'is_gallery_page',
        'is_career_page',
        'is_contact_page',
        'is_quote_page',
        'is_about_about',
        'is_about_w_w_a',
        'is_about_choose_us',
        'is_about_history',
        'is_whatsapp',
        'is_call_button',
        'is_video_hero',
        'is_preloader',
        'is_shop',
        'is_about_featured_work',
        'is_user_system',
        'is_shop_share_links',
        'is_t1_slider_section',
        'is_t1_about_section',
        'is_t1_featured_work_section',
        'is_t1_who_we_are_section',
        'is_t1_service_section',
        'is_t1_portfolio_section',
        'is_t1_team_section',
        'is_t1_counter_section',
        'is_t1_testimonial_section',
        'is_t1_meet_us_section',
        'is_t1_blog_section',
        'is_t1_clint_section',
        'is_t2_slider_section',
        'is_t2_who_we_are_section',
        'is_t2_service_section',
        'is_t2_portfolio_section',
        'is_t2_team_section',
        'is_t2_testimonial_section',
        'is_t2_faq_section',
        'is_t2_news_section',
        'is_t2_client_section',
        'is_t3_hero_section',
        'is_t3_about_section',
        'is_t3_service_section',
        'is_t3_intro_video_section',
        'is_t3_team_section',
        'is_t3_counter_section',
        'is_t3_testimonial_section',
        'is_t3_faq_section',
        'is_t3_meet_us_section',
        'is_t3_news_section',
        'is_t3_client_section',
    ];
}
